# Generated by Django 2.2.3 on 2019-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='computer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
