# Generated by Django 2.2.3 on 2019-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccoapp', '0002_transaction_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='companySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(upload_to='')),
                ('branchName', models.CharField(max_length=100)),
                ('minimum_account_balance', models.IntegerField(max_length=50)),
            ],
        ),
    ]
