# Generated by Django 2.2.3 on 2019-08-03 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saccoapp', '0003_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='deposit_charges',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='withdraw_charges',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='TellerAccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
