# Generated by Django 2.2.3 on 2019-08-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saccoapp', '0005_auto_20190803_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsearch',
            name='accounts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saccoapp.Member'),
        ),
        migrations.CreateModel(
            name='GroupAccountSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saccoapp.Group')),
            ],
        ),
    ]
