# Generated by Django 2.2.3 on 2019-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccoapp', '0006_auto_20190804_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('transaction_account', models.IntegerField(max_length=100, null=True)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0, max_length=100)),
                ('transacted_by', models.CharField(max_length=100)),
                ('slip_number', models.CharField(max_length=100)),
                ('transacting_staff', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('charges', models.CharField(default='', max_length=100, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('computer', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
