# Generated by Django 2.2.3 on 2019-08-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccoapp', '0007_groupaccounttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='telleraccountbalance',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
