# Generated by Django 2.2.3 on 2019-08-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saccoapp', '0008_telleraccountbalance_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_deposit', models.BooleanField(default=False)),
                ('can_withdraw', models.BooleanField(default=False)),
                ('can_register', models.BooleanField(default=False)),
                ('can_handle_loans', models.BooleanField(default=False)),
                ('can_send_balance', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
